language: c
os:
  - linux
  - osx
arch:
  - amd64
  # - ppc64le  # Apply patch
  - arm64
services:
  - redis

install: 
  - ci-base/install.sh
  - install.sh
script: ./run.sh
jobs:
  exclude:
  - os: osx
    arch: ppc64le
  - os: osx
    arch: arm64
